name: 🙂 Add new emote
description: Suggest new emote
title: "Add new emote: "
labels: ["new-emote"]
assignees:
  - rilaveon
  
body:
  - type: dropdown
    id: type
    attributes:
      label: Emote Type
      options:
        - Twitch Animated Emote
        - BetterTTV Animated Emote
        - Telegram Sticker
        - Uploaded Image
    validations:
      required: true
      
  - type: input
    id: emotename
    attributes:
      label: Emote Name
      placeholder: ex. forsenPls
    validations:
      required: true
      
  - type: input
    id: emoteid
    attributes:
      label: Emote ID
      description: |
                   How to get emote ID:
                   
                   - Twitch Animated Emote: 
                     https:\/\/static-cdn.jtvnw.net/emoticons/v2/emotesv2_<ins>**bde78453ef2a40bf95e6ece9c7420f7c**</ins>/default/dark/3.0
                   - BetterTTV Animated Emote: 
                     https:\/\/cdn.betterttv.net/emote/<ins>**614f3316b63cc97ee6d33e1c**</ins>/3x
                   - Telegram Sticker
                     Contact @rilaveon for adding to [sticker pack](https://t.me/addstickers/peepoChat)
                   - Uploaded Image: 
                     https:\/\/i.imgur.com/<ins>**QUBCtxn**</ins>.gif 
                     Convert animated image to GIF and upload to Imgur. Upload as anonymous
    validations:
      required: true
