name: Add new emote
description: For staff
title: "[Emote]: "
labels: ["new-emote"]
assignees:
  - rilaveon
body:
  - type: dropdown
    id: type
    attributes:
      label: Emote type
      options:
        - Twitch Animated Emote
        - BetterTTV Animated Emote
        - Telegram Sticker
    validations:
      required: true
      
  - type: input
    id: emotename
    attributes:
      label: Emote Name
      placeholder: ex. forsenPls
    validations:
      required: true
      
  - type: input
    id: emoteid
    attributes:
      label: Emote ID
      description: |
                   Test
                   123
      placeholder: ex. forsenPls
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
