name: YAML to JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Convert YAML to JSON
        uses: fabasoad/yaml-json-xml-converter-action@main
        with:
          path: 'db/all.yaml'
          from: 'yaml'
          to: 'json'
